name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, windows-2022, ubuntu-18.04]
        goVer: [1.12, 1.13, 1.14, 1.15, 1.16, 1.17]

    steps:
    - name: Set up Go ${{ matrix.goVer }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.goVer }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Change Permissions
      shell: bash
      run: chmod 400 unwritable_config_test.json
    
    - name: Get Dependencies
      shell: bash
      run: |
        go get -v -t -d ./...	
        if [ -f Gopkg.toml ]; then	
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh	
            dep ensure	
        fi	
        chmod 400 unwritable_config_test.json

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
